[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"
solana_version = "1.17.10"
# docker_image = "backpackapp/build:v0.31.1"


[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
recru_search = "BkXcFAo2TFkXRm9WsKUxikgNYvvR3Pm3yS9xLdqaeJoo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/orinthundershield/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
